services:
  db:
    image: postgres:15
    container_name: ob_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./deploy/postgres/:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: